name: Build and Deploy Docusaurus with KDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [kotlin-repo-updated]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Docusaurus with KDocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docusaurus Repository
        uses: actions/checkout@v4
        with:
          path: docusaurus-repo

      - name: Checkout Kotlin Repository
        uses: actions/checkout@v4
        with:
          repository: VishnuSanal/multipaz-identity-credential
          path: kotlin-repo
          ref: 'main'
          fetch-depth: 0
          fetch-tags: true

      - name: Get Kotlin Repo Commit Hash
        id: kotlin-commit
        run: |
          cd kotlin-repo
          COMMIT_HASH=$(git rev-parse HEAD)
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "Latest commit hash: $COMMIT_HASH"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Cache the Dokka output using the commit hash
      - name: Cache KDocs
        id: cache-kdocs
        uses: actions/cache@v3
        with:
          path: kotlin-repo/build/dokka
          key: kdocs-${{ steps.kotlin-commit.outputs.commit_hash }}

      # Only run Dokka if there was a cache miss
      - name: Generate KDocs with Dokka
        if: steps.cache-kdocs.outputs.cache-hit != 'true'
        run: |
          cd kotlin-repo
          ./gradlew dokkaHtmlMultiModule
          echo "KDocs generated successfully"
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: docusaurus-repo/package-lock.json

      - name: Create API directory in Docusaurus static folder
        run: mkdir -p docusaurus-repo/static/kdocs

      - name: Copy KDocs and markdown files to Docusaurus
        run: ./docusaurus-repo/copy_docs.sh

      - name: Install Docusaurus dependencies
        run: |
          cd docusaurus-repo
          npm ci

      - name: Build Docusaurus website
        run: |
          cd docusaurus-repo
          # Include the current date in the build for versioning
          echo "Build date: $(date +'%Y-%m-%d %H:%M:%S')" > src/build-info.json
          npm run build
        env:
          NODE_ENV: production
          DOCUSAURUS_URL: https://${{ github.repository_owner }}.github.io
          DOCUSAURUS_BASEURL: ${{ github.event.repository.name }}/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docusaurus-repo/build

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
